# Generated by Django 5.2.6 on 2025-11-17 15:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.IntegerField(help_text='Número del nivel (1-20)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('nombre', models.CharField(help_text='Nombre del nivel (ej: Principiante, Intermedio)', max_length=100)),
                ('puntos_minimos', models.IntegerField(help_text='Puntos mínimos requeridos para alcanzar este nivel', validators=[django.core.validators.MinValueValidator(0)])),
                ('puntos_maximos', models.IntegerField(blank=True, help_text='Puntos máximos para este nivel (null si es el nivel máximo)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('icono', models.CharField(blank=True, help_text='Emoji o código de icono', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Nivel',
                'verbose_name_plural': 'Configuraciones de Niveles',
                'db_table': 'configuracion_niveles',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='ReglaGamificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_regla', models.CharField(choices=[('puntos_completar_mision', 'Puntos por Completar Misión'), ('puntos_entrega_tardia', 'Puntos por Entrega Tardía'), ('puntos_entrega_anticipada', 'Puntos por Entrega Anticipada'), ('multiplicador_dificultad_facil', 'Multiplicador Dificultad Fácil'), ('multiplicador_dificultad_medio', 'Multiplicador Dificultad Medio'), ('multiplicador_dificultad_dificil', 'Multiplicador Dificultad Difícil'), ('puntos_bonificacion_primera_vez', 'Bonificación Primera Vez'), ('puntos_bonificacion_racha', 'Bonificación por Racha')], max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor numérico de la regla (puntos o multiplicador)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la regla')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Gamificación',
                'verbose_name_plural': 'Reglas de Gamificación',
                'db_table': 'reglas_gamificacion',
                'ordering': ['tipo_regla'],
            },
        ),
    ]
