# Generated by Django 5.2.6 on 2025-11-24 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVisual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_url', models.CharField(blank=True, help_text='URL del logo de la institución', max_length=500, null=True)),
                ('nombre_institucion', models.CharField(default='EduQuest', help_text='Nombre de la institución', max_length=200)),
                ('color_primario', models.CharField(default='#3B82F6', help_text='Color primario en formato hexadecimal (ej: #3B82F6)', max_length=7)),
                ('color_secundario', models.CharField(default='#6366F1', help_text='Color secundario en formato hexadecimal (ej: #6366F1)', max_length=7)),
                ('color_acento', models.CharField(default='#8B5CF6', help_text='Color de acento en formato hexadecimal (ej: #8B5CF6)', max_length=7)),
                ('color_fondo', models.CharField(default='#F9FAFB', help_text='Color de fondo en formato hexadecimal (ej: #F9FAFB)', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Visual',
                'verbose_name_plural': 'Configuraciones Visuales',
                'db_table': 'configuracion_visual',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
