# Generated by Django 5.2.6 on 2025-11-04 11:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_curso', models.CharField(help_text='Código único del curso (ej: MAT101)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nombre', models.CharField(help_text='Nombre del curso', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del curso', null=True)),
                ('imagen_portada', models.CharField(blank=True, help_text='URL de la imagen de portada', max_length=255, null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio del curso', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin del curso', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el curso está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_profesor', models.CharField(choices=[('titular', 'Titular'), ('asistente', 'Asistente')], default='titular', help_text='Rol del profesor en el curso', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='profesores_asignados', to='cursos.curso')),
                ('profesor', models.ForeignKey(db_column='profesor_id', limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Profesor-Curso',
                'verbose_name_plural': 'Asignaciones Profesor-Curso',
                'db_table': 'cursos_profesores',
                'managed': True,
                'unique_together': {('curso', 'profesor')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('retirado', 'Retirado')], default='activo', max_length=20)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'managed': True,
                'indexes': [models.Index(fields=['estudiante', 'estado'], name='inscripcion_estudia_041e73_idx'), models.Index(fields=['curso', 'estado'], name='inscripcion_curso_i_de156d_idx')],
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
