# Generated by Django 5.2.6 on 2025-11-04 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_profesor', models.CharField(choices=[('titular', 'Titular'), ('asistente', 'Asistente')], default='titular', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='profesores_asignados', to='cursos.curso')),
                ('profesor', models.ForeignKey(db_column='profesor_id', limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Profesor',
                'verbose_name_plural': 'Asignaciones de Profesores',
                'db_table': 'cursos_profesores',
                'ordering': ['-fecha_asignacion'],
                'managed': True,
                'indexes': [models.Index(fields=['curso', 'rol_profesor'], name='cursos_prof_curso_i_efa4cf_idx'), models.Index(fields=['profesor'], name='cursos_prof_profeso_2ed23b_idx')],
                'unique_together': {('curso', 'profesor')},
            },
        ),
    ]
